name: Dev Container Build
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'staging'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: npm install && npm run build

