/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.4.1-18421
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OpenIDConfig } from '../models/OpenIDConfig';
import { HttpFile } from '../http/http';

/**
* 
*/
export class DomainAuthProviderResponse {
    /**
    * Provider ID
    */
    'identifier': string;
    /**
    * Provider ID for backward compatibility with frontend
    */
    'id'?: string | null;
    /**
    * Provider Type
    */
    'providerType': string;
    /**
    * Provider Type for backward compatibility with frontend
    */
    'provider'?: string | null;
    /**
    * Login Button Text
    */
    'label': string;
    /**
    * Title Text for the Frontend\'s Provider Configuration Form
    */
    'name'?: string | null;
    /**
    * Coordinator endpoint for Authorizing with this provider
    */
    'authorizationUrl'?: string | null;
    /**
    * True: Configured in coordinator.json, False: Custom Domain Provider
    */
    '_default': boolean;
    /**
    * Enabled/Disabled
    */
    'enabled': boolean;
    'config'?: OpenIDConfig;
    /**
    * Optional User ID of creator
    */
    'createdBy'?: string | null;
    /**
    * Created Date in ISO-8601 format e.g. 2022-05-06T02:39:23.000Z
    */
    'createdAt': string;
    /**
    * Updated Date in ISO-8601 format e.g. 2022-05-06T02:39:23.000Z
    */
    'updatedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerType",
            "baseName": "providerType",
            "type": "string",
            "format": ""
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorizationUrl",
            "baseName": "authorizationUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "OpenIDConfig",
            "format": ""
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DomainAuthProviderResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

