/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 6.0.0-20323
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnapshotPermissions } from '../models/SnapshotPermissions';
import { TrialExtension } from '../models/TrialExtension';
import { HttpFile } from '../http/http';

/**
* 
*/
export class DomainOptions {
    /**
    * if true, totp is required
    */
    'totpRequired'?: boolean | null;
    'trialExtension'?: TrialExtension;
    'snapshotPermissions'?: SnapshotPermissions;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totpRequired",
            "baseName": "totpRequired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "trialExtension",
            "baseName": "trialExtension",
            "type": "TrialExtension",
            "format": ""
        },
        {
            "name": "snapshotPermissions",
            "baseName": "snapshotPermissions",
            "type": "SnapshotPermissions",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DomainOptions.attributeTypeMap;
    }

    public constructor() {
    }
}

