/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.4.1-18421
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OpenIDConfig } from '../models/OpenIDConfig';
import { HttpFile } from '../http/http';

/**
* 
*/
export class DomainAuthProviderRequest {
    /**
    * Provider Type
    */
    'providerType': string;
    /**
    * Enabled/Disabled
    */
    'enabled': boolean;
    /**
    * Login Button Text
    */
    'label'?: string | null;
    'config'?: OpenIDConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "providerType",
            "baseName": "providerType",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "OpenIDConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DomainAuthProviderRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

