/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.6.0-19122
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class Firmware {
    /**
    * 
    */
    'version'?: string | null;
    /**
    * 
    */
    'buildid'?: string | null;
    /**
    * Android only flavor
    */
    'androidFlavor'?: string | null;
    /**
    * Android only API version
    */
    'aPIVersion'?: string | null;
    /**
    * 
    */
    'sha256sum'?: string | null;
    /**
    * 
    */
    'sha1sum'?: string | null;
    /**
    * 
    */
    'md5sum'?: string | null;
    /**
    * 
    */
    'size'?: number | null;
    /**
    * 
    */
    'uniqueId'?: string | null;
    /**
    * Firmware metadata
    */
    'metadata'?: any | null;
    /**
    * Release Date
    */
    'releasedate'?: Date | null;
    /**
    * Date uploaded
    */
    'uploaddate'?: Date | null;
    /**
    * URL firmware is available at
    */
    'url'?: string | null;
    /**
    * URL firmware is available at from vendor
    */
    'origUrl'?: string | null;
    /**
    * 
    */
    'filename'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildid",
            "baseName": "buildid",
            "type": "string",
            "format": ""
        },
        {
            "name": "androidFlavor",
            "baseName": "AndroidFlavor",
            "type": "string",
            "format": ""
        },
        {
            "name": "aPIVersion",
            "baseName": "APIVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256sum",
            "baseName": "sha256sum",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha1sum",
            "baseName": "sha1sum",
            "type": "string",
            "format": ""
        },
        {
            "name": "md5sum",
            "baseName": "md5sum",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        },
        {
            "name": "uniqueId",
            "baseName": "uniqueId",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "releasedate",
            "baseName": "releasedate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "uploaddate",
            "baseName": "uploaddate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "origUrl",
            "baseName": "orig_url",
            "type": "string",
            "format": "url"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Firmware.attributeTypeMap;
    }

    public constructor() {
    }
}

