/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.2.0-17376
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VpnDefinition } from '../models/VpnDefinition';
import { HttpFile } from '../http/http';

/**
* 
*/
export class InstanceServices {
    'vpn'?: VpnDefinition;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "vpn",
            "baseName": "vpn",
            "type": "VpnDefinition",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InstanceServices.attributeTypeMap;
    }

    public constructor() {
    }
}

