/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 4.3.1-16664
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TextInput } from '../models/TextInput';
import { TouchCurveInput } from '../models/TouchCurveInput';
import { TouchInput } from '../models/TouchInput';
import { HttpFile } from '../http/http';

/**
* 
*/
export class InstanceInput {
    /**
    * Finger Positions
    */
    'position'?: any;
    /**
    * Finger Positions
    */
    'start'?: any;
    /**
    * Finger Positions
    */
    'end'?: any;
    /**
    * text to type
    */
    'text'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "position",
            "baseName": "position",
            "type": "any",
            "format": "up to 10"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "any",
            "format": "up to 10"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "any",
            "format": "up to 10"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InstanceInput.attributeTypeMap;
    }

    public constructor() {
    }
}

