/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 4.3.1-16664
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Current Instance State
*/
export type InstanceState = "on" | "off" | "booting" | "deleting" | "creating" | "restoring" | "paused" | "rebooting" | "error" ;
