/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.0.0-17089
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KernelThread } from '../models/KernelThread';
import { HttpFile } from '../http/http';

/**
* 
*/
export class KernelTask {
    /**
    * Kernel Task ID
    */
    'kernelId'?: string | null;
    /**
    * Thread name
    */
    'name'?: string | null;
    /**
    * Process ID of task
    */
    'pid'?: number | null;
    /**
    * 
    */
    'threads'?: Array<KernelThread> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "kernelId",
            "baseName": "kernelId",
            "type": "string",
            "format": "uint64_t"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "pid",
            "baseName": "pid",
            "type": "number",
            "format": ""
        },
        {
            "name": "threads",
            "baseName": "threads",
            "type": "Array<KernelThread>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KernelTask.attributeTypeMap;
    }

    public constructor() {
    }
}

