/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 6.1.0-20784
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class MeteredSubscriptionUsage {
    /**
    * Unit price
    */
    'burstRate'?: number | null;
    /**
    * Allocated hours
    */
    'allocatedHours'?: number | null;
    /**
    * Plan cost
    */
    'planBilledAmount'?: number | null;
    /**
    * Units included in plan
    */
    'planBilledUnits'?: number | null;
    /**
    * Amount billed
    */
    'burstBilledAmount'?: number | null;
    /**
    * Units billed
    */
    'burstBilledUnits'?: number | null;
    /**
    * Outstanding amount
    */
    'burstOutstandingAmount'?: number | null;
    /**
    * Outstanding units
    */
    'burstOutstandingUnits'?: number | null;
    /**
    * Total cost in cents for current period
    */
    'totalUsageAmount'?: number | null;
    /**
    * Total used units for current period
    */
    'totalUsedUnits'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "burstRate",
            "baseName": "burst_rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "allocatedHours",
            "baseName": "allocated_hours",
            "type": "number",
            "format": ""
        },
        {
            "name": "planBilledAmount",
            "baseName": "plan_billed_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "planBilledUnits",
            "baseName": "plan_billed_units",
            "type": "number",
            "format": ""
        },
        {
            "name": "burstBilledAmount",
            "baseName": "burst_billed_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "burstBilledUnits",
            "baseName": "burst_billed_units",
            "type": "number",
            "format": ""
        },
        {
            "name": "burstOutstandingAmount",
            "baseName": "burst_outstanding_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "burstOutstandingUnits",
            "baseName": "burst_outstanding_units",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalUsageAmount",
            "baseName": "total_usage_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalUsedUnits",
            "baseName": "total_used_units",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MeteredSubscriptionUsage.attributeTypeMap;
    }

    public constructor() {
    }
}

