/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.7.1-19698
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class PasswordResetBody {
    /**
    * Password reset token
    */
    'token': string;
    /**
    * Password reset totpToken
    */
    'totpToken': string;
    /**
    * new password
    */
    'newPassword': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "totpToken",
            "baseName": "totpToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "newPassword",
            "baseName": "new-password",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PasswordResetBody.attributeTypeMap;
    }

    public constructor() {
    }
}

