/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.6.0-19122
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InstanceBootOptions } from '../models/InstanceBootOptions';
import { ProxyConfig } from '../models/ProxyConfig';
import { HttpFile } from '../http/http';

/**
* 
*/
export class PatchInstanceOptions {
    /**
    * the name of the device
    */
    'name'?: string | null;
    /**
    * the desired state of the device
    */
    'state'?: PatchInstanceOptionsStateEnum | null;
    'bootOptions'?: InstanceBootOptions;
    /**
    * 
    */
    'proxy'?: Array<ProxyConfig> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "PatchInstanceOptionsStateEnum",
            "format": ""
        },
        {
            "name": "bootOptions",
            "baseName": "bootOptions",
            "type": "InstanceBootOptions",
            "format": ""
        },
        {
            "name": "proxy",
            "baseName": "proxy",
            "type": "Array<ProxyConfig>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PatchInstanceOptions.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PatchInstanceOptionsStateEnum = "on" | "off" | "paused" | "deleting" ;

