/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 4.3.1-16664
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Plan options
*/
export class Plan {
    /**
    * 
    */
    'licenseType': PlanLicenseTypeEnum;
    /**
    * Number of CPU cores
    */
    'cores': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "licenseType",
            "baseName": "licenseType",
            "type": "PlanLicenseTypeEnum",
            "format": ""
        },
        {
            "name": "cores",
            "baseName": "cores",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Plan.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PlanLicenseTypeEnum = "premium" | "individual" | "standard" | "enterprise" | "individual-usage" | "enterprise-usage" | "unrestricted" ;

