/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 4.3.1-16664
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class ProjectSettings {
    /**
    * 
    */
    'version'?: number | null;
    /**
    * 
    */
    'internetAccess'?: boolean | null;
    /**
    * 
    */
    'dhcp'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": ""
        },
        {
            "name": "internetAccess",
            "baseName": "internet-access",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dhcp",
            "baseName": "dhcp",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProjectSettings.attributeTypeMap;
    }

    public constructor() {
    }
}

