/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.2.0-17376
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Represents a Proxy configuration object.
*/
export class ProxyConfig {
    /**
    * The device port to use for proxying.
    */
    'devicePort'?: number | null;
    /**
    * If `true`, the first available port will be used if `devicePort` is not available.
    */
    'firstAvailable'?: boolean | null;
    /**
    * If `true`, the proxy will be exposed to the external interface.
    */
    'expose'?: boolean | null;
    /**
    * The router port to use for proxying.
    */
    'routerPort'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "devicePort",
            "baseName": "devicePort",
            "type": "number",
            "format": ""
        },
        {
            "name": "firstAvailable",
            "baseName": "firstAvailable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expose",
            "baseName": "expose",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "routerPort",
            "baseName": "routerPort",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProxyConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

