/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 6.1.0-20784
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnapshotSharing } from '../models/SnapshotSharing';
import { SnapshotStatus } from '../models/SnapshotStatus';
import { HttpFile } from '../http/http';

/**
* 
*/
export class Snapshot {
    /**
    * Snapshot ID
    */
    'id': string;
    /**
    * Snapshot name
    */
    'name': string;
    /**
    * Instance that this snapshot is of
    */
    'instance': string;
    'status': SnapshotStatus;
    /**
    * UNIX Date that the snapshot was created
    */
    'date': number;
    /**
    * 
    */
    'fresh': boolean;
    /**
    * Live snapshot (included state and memory)
    */
    'live': boolean;
    /**
    * 
    */
    'local': boolean;
    'sharing'?: SnapshotSharing;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SnapshotStatus",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "number",
            "format": ""
        },
        {
            "name": "fresh",
            "baseName": "fresh",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "live",
            "baseName": "live",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "local",
            "baseName": "local",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sharing",
            "baseName": "sharing",
            "type": "SnapshotSharing",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Snapshot.attributeTypeMap;
    }

    public constructor() {
    }
}

