/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 6.0.0-20323
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnapshotInvitationTypes } from '../models/SnapshotInvitationTypes';
import { HttpFile } from '../http/http';

/**
* 
*/
export class SnapshotPermissions {
    /**
    * Indicates if snapshot permissions are enabled
    */
    'enabled'?: boolean | null;
    'invitationTypes'?: SnapshotInvitationTypes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "invitationTypes",
            "baseName": "invitationTypes",
            "type": "SnapshotInvitationTypes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnapshotPermissions.attributeTypeMap;
    }

    public constructor() {
    }
}

