/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 6.1.0-20784
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SnapshotUser } from '../models/SnapshotUser';
import { HttpFile } from '../http/http';

/**
* 
*/
export class SnapshotSharing {
    /**
    * The URL of the snapshot.
    */
    'url': string;
    /**
    * The users who have access to the snapshot.
    */
    'users': Array<SnapshotUser>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<SnapshotUser>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnapshotSharing.attributeTypeMap;
    }

    public constructor() {
    }
}

