/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 6.1.0-20784
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class SnapshotPermissions {
    /**
    * Indicates if snapshot permissions are enabled
    */
    'enabled'?: boolean | null;
    /**
    * Indicates if public link access is enabled
    */
    'publicLink'?: boolean | null;
    /**
    * Indicates if domain-restricted link access is enabled
    */
    'domainRestrictedLink'?: boolean | null;
    /**
    * Indicates if password-protected public link access is enabled
    */
    'passwordPublicLink'?: boolean | null;
    /**
    * Indicates if email invite access is enabled
    */
    'emailInvite'?: boolean | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "publicLink",
            "baseName": "publicLink",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "domainRestrictedLink",
            "baseName": "domainRestrictedLink",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "passwordPublicLink",
            "baseName": "passwordPublicLink",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "emailInvite",
            "baseName": "emailInvite",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SnapshotPermissions.attributeTypeMap;
    }

    public constructor() {
    }
}

