/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.5.0-18750
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class TouchInput {
    /**
    * Finger Positions
    */
    'position'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "position",
            "baseName": "position",
            "type": "any",
            "format": "up to 10"
        }    ];

    static getAttributeTypeMap() {
        return TouchInput.attributeTypeMap;
    }

    public constructor() {
    }
}

