/**
 * Corellium API
 * REST API to manage your virtual devices.
 *
 * OpenAPI spec version: 5.5.0-18750
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 
*/
export class VpnDefinition {
    /**
    * 
    */
    'proxy'?: Array<any> | null;
    /**
    * 
    */
    'listeners'?: Array<any> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "proxy",
            "baseName": "proxy",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "listeners",
            "baseName": "listeners",
            "type": "Array<any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VpnDefinition.attributeTypeMap;
    }

    public constructor() {
    }
}

